name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build build-essential

      - name: Configure
        run: cmake -B build -G Ninja

      - name: Build
        run: cmake --build build

      - name: Smoke test
        run: ./build/regress --help
